### ISSUE TITLE
Add support for affinity in the k8s spec in a workflow

### ISSUE THREAD

**Issue by dustinblack** [arcalot/arcaflow-engine-deployer-kubernetes#1]
## Please describe what you would like to see in this project

Currently the `affinity` feature of the k8s API is not supported in the `spec` parameters for a workflow plugin. This is a critical feature for ensuring pods are co-located or explicitly avoid co-location on the same nodes.

```
2022-11-22T10:51:15Z	info		Starting step metadata...
2022-11-22T10:51:15Z	error		Workflow execution failed (failed to unserialize deployer config for step metadata (Validation failed for 'pod' -> 'spec': Invalid parameter 'affinity', expected one of: initContainers, containers, pluginContainer, volumes))
exit status 1
```

## Please describe your use case

When scheduling a metadata or metrics collection plugin alongside a workload plugin, it is critical that these plugins run on the same nodes in the cluster.

Sample workflow snippet:
```yaml
  metadata:
    plugin: quay.io/arcalot/arcaflow-plugin-metadata:latest
    deploy:
      type: kubernetes
      connection: !expr $.steps.kubeconfig.outputs.success.connection
      pod:
        metadata:
          namespace: default
          labels:
            arcaflow: metadata
        spec:
          pluginContainer:
            imagePullPolicy: Always
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: arcaflow
                    operator: In
                    values:
                    - uperf-client
    input: {}
```

**Comment by dustinblack** [comment]
Needs to be added here: https://github.com/arcalot/arcaflow-engine-deployer-kubernetes/blob/main/schema.go#L838

**Comment by josecastillolema** [comment]
One quick comment, the provided podAffinity wont work on k8s:
```
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: arcaflow
                    operator: In
                    values:
                    - uperf-client
```

`error: error validating "pod.yaml": error validating data: ValidationError(Pod.spec.affinity.podAffinity.requiredDuringSchedulingIgnoredDuringExecution[0]): missing required field "topologyKey" in io.k8s.api.core.v1.PodAffinityTerm`

From the docs: Pod anti-affinity requires nodes to be consistently labelled, in other words, every node in the cluster must have an appropriate label matching **topologyKey**. If some or all nodes are missing the specified topologyKey label, it can lead to unintended behavior.

So you need something like:
```
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: arcaflow
                    operator: In
                    values:
                    - uperf-client
                 topologyKey: node-role.kubernetes.io/worker
```
